imgsz: 960
epochs: 50
batch: 16
optimizer: AdamW
cos_lr: true
patience: 20
close_mosaic: 5
augment: true
hsv_h: 0.005
hsv_s: 0.3
hsv_v: 0.3
degrees: 1.0
translate: 0.02
scale: 0.1
shear: 0.0
flipud: 0.0
fliplr: 0.0
